### ISSUE TITLE
path for fping issues

### ISSUE THREAD

**Issue by Gilgalidd** [phpipam/phpipam-agent#1]
Hello,

I've a problem with fping path, here is my config file:

```
$config['method']       = "fping";
#$config['pingpath'] = "/usr/local/sbin/fping";
$config['pingpath'] = "/usr/bin/fping";
```
And the error:
```
/var/www/phpipam-agent# php index.php discover
sh: 1: /bin/fping: not found

/var/www/phpipam-agent# which fping
/usr/bin/fping
``` 

When I do a link to the path specified in the error It works well, maybe it's better to use env. variable instead of specified the path in conf. file?
```
ln -s /usr/bin/fping /bin/fping
```

**Comment by phpipam** [comment]
Hi, thanks for testing. Indeed settings were taken from main database and not from config.php . Should be fixed now, please test.

**Comment by Gilgalidd** [comment]
It works !

Thanks.
