### ISSUE TITLE
ipv6 support?

### ISSUE THREAD

**Issue by mgdudas** [phpipam/phpipam-agent#10]
Hi,

I'm trying to use the agent to scan my public ipv6 subnet, which is a /64, but I get this message:

Error: netmask must be between 1 and 30 (is: 64)

I had changed pingpath in the configuration to use fping6 in order to get this far. But I'm not sure where this restriction is.

Thanks!

**Comment by GaryAllan** [comment]
IPv6 subnets are too large to ping sweep.

Thanks

**Comment by mgdudas** [comment]
That's a pretty ridiculous response to make over 3 years later on this issue. This blog post from over 11 years ago addresses exactly this kind of question. 

https://insights.sei.cmu.edu/cert/2008/09/ping-sweeping-in-ipv6.html

**Comment by GaryAllan** [comment]
Hello @mgdudas 
The techniques described in the article are only valid for directly attached subnets. They're not helpful for scanning remote IPv6 subnets using phpipam-agent.

**Comment by mgdudas** [comment]
I believe a IPv6 network that a host is on, is by definition directly attached? It's not like I'm trying to use it to scan over the open internet.

Obviously this is 3 years old. I'm just disappointed by the sudden closure after so long. Thank you for at least replying. Have a nice day.

**Comment by Queuecumber** [comment]
@GaryAllan I have to agree with @mgdudas it should be trivial to implement

```
ping6 -B -I eth0 -I [global IPv6 address attached to eth0] ff02::1
```

and examine the neighbor cache, functionally I don't see how this is different from how the ipv4 scan is carried out
