### ISSUE TITLE
Scan-Agent Error when multiple subnet is enabled

### ISSUE THREAD

**Issue by linuxmkd** [phpipam/phpipam-agent#11]
When multiple subnet is enbled on the same scan-agent we got an error on the discover process

```
php index.php discover
--------------------
Error: Didn't find any address to scan!
--------------------
```

**Comment by CoMPaTech** [comment]
Will need @phpipam to elaborate on this precisely but had this issue myself. To clarfiy "discovery won't work when at least 1 of your subnets is 100% full".

The quick fix is to edit ```functions/classes/class.Scan.php``` and line 625 (where there is if sizeof ip and the exception error) put a ```#``` or ```//``` in front of the if statement

@phpipam I can see why you'd now want to discover a single subnet, but throwing the exception to break out is a bit harsh :) Didn't have time to create a better solution or pullreq (yet), sorry.

**Comment by phpipam** [comment]
This should fix it. f5367c5

**Comment by JujubeT** [comment]
> 将需要@phpipam进行详细说明，但我自己遇到了这个问题。为了澄清“如果至少有一个子网100％充满，则发现将不起作用”。
> 
> 快速的解决方法是编辑`functions/classes/class.Scan.php`625行（其中有if sizeof ip和异常错误），在if语句前放置a `#`或`//`
> 
> @phpipam我明白了为什么您现在想发现一个子网，但是抛出异常来破解有点苛刻：)还没来得及创建更好的解决方案或pullreq（抱歉）。

Thank you, this is useful!
