### ISSUE TITLE
Error at end of running the remote Agent

### ISSUE THREAD

**Issue by flexyz-support** [phpipam/phpipam-agent#18]
When running the remote agent on multiple subnets, I get an error at the end:
Error: SQLSTATE[42000]: Syntax error or access violation: 1142 DELETE command denied to user 'agent'@'10.10.10.10' for table 'ipaddresses'

I have followed the readme to create the "agent" user account in MySQL. In the mentioned GRANT commands there is not one with Delete rights.

Everything else seems to work...
Do we need to grand Delete rights and on which tables?

**Comment by phpipam** [comment]
Yes, seems that instructions are wrong/incomplete, will update. This is related to PR https://github.com/phpipam/phpipam-agent/pull/13 that deletes inactive DHCP addresses.

I will also add option to remove DHCP addresses to prevent this by default.

You need DELETE grants on `ipaddresses` table.

**Comment by phpipam** [comment]
Fixed. Update config.php if you need removal.
