### ISSUE TITLE
Subnet (/25) not scanned

### ISSUE THREAD

**Issue by flexyz-support** [phpipam/phpipam-agent#19]
We have multiple subnets that we scan with the PHPIPAM remote agent.
With one /25 subnet we have a problem, while an other works fine...
The two subnets:
- 172.31.100.0/25 -> This subnet is not scanned (No output on the console and no updates on de db)
- 172.31.100.129/25 -> This subnet is scanned fine.

This is how they are both stored in the database (the one with id-81 runs ok):
*************************** 1. row ***************************
id: 81
subnet: 2887738496
mask: 25
sectionId: 13
description: hrd01 Services
firewallAddressObject: NULL
vrfId: 1
masterSubnetId: 0
allowRequests: 0
vlanId: 6
showName: 1
device: 0
permissions: {"2":"2","3":"1"}
pingSubnet: 1
discoverSubnet: 1
DNSrecursive: 0
DNSrecords: 0
nameserverId: 0
scanAgent: 10
isFolder: 0
isFull: 0
state: 2
Location: NULL
editDate: 2017-02-16 11:02:37
*************************** 2. row ***************************
id: 171
subnet: 2887738368
mask: 25
sectionId: 13
description: ape01 Services
firewallAddressObject: NULL
vrfId: 1
masterSubnetId: 0
allowRequests: 0
vlanId: 6
showName: 1
device: 0
permissions: {"2":"2","3":"1"}
pingSubnet: 1
discoverSubnet: 1
DNSrecursive: 0
DNSrecords: 0
nameserverId: 0
scanAgent: 10
isFolder: 0
isFull: 0
state: 2
Location: NULL
editDate: 2017-02-16 11:02:06
2 rows in set (0.00 sec)

How can I get them both to be scanned?

**Comment by flexyz-support** [comment]
I did some more testing:
I deleted both /25 subnets....
When I create a new subnet (ie. 192.168.192.0/24) it is not scanned with the command "php index.php update".
When I run the command "php index.php configure" I get the message: 
- Error: Didn't find any address to scan!

Running the remote agent on an other machine on an other network seems to run fine...

Any thoughts?

**Comment by phpipam** [comment]
Hi,

`php index.php update` will try to update status of EXISTING addresses in subnets marked with `Hosts check`.
`php index.php discover` will search for NEW addresses in sunbets that are marked with `Discover new hosts`

br

**Comment by flexyz-support** [comment]
I have found the problem. In the config file there was a typo in the hostname. 
We have installed several remote agents and all seem to work, but the one with the /25 subnet.
Strange how one half of the /25 subnets worked and the other didn't, but after I changed the hostname, both worked.
So this issue can be closed... Miha, thanks for your support!!!

**Comment by phpipam** [comment]
Great. Br
