### ISSUE TITLE
Update/Discover

### ISSUE THREAD

**Issue by Gilgalidd** [phpipam/phpipam-agent#2]
Hello,

I didn't notice any difference between update and discover.
The update shouldn't only ping discovered hosts, not do a discover of entire range ?

**Comment by mail3dexter** [comment]
+1

**Comment by ack-martijng** [comment]
Update does not perform discovery,

**Comment by GaryAllan** [comment]
fping will scan all hosts (update+discovery)
ping discovery will ping all hosts
ping update will only ping existing hosts

Closing old thread. Please re-open if issue is still present.
Thank you
