### ISSUE TITLE
Php function long2ip() arguments

### ISSUE THREAD

**Issue by Gilgalidd** [phpipam/phpipam-agent#20]
Hello,

When I run a discovery, the long2ip() function is run with a string as argument. 
Apparently, php need an int now.

> PHP Warning:  long2ip() expects parameter 1 to be integer, string given in <path>\phpipam-agent-master\functions\classes\class.Common.php on line 347

In the [long2ip() documentation](https://secure.php.net/manual/en/function.long2ip.php), the arg should be a string:
```php
string long2ip ( string $proper_address )
``` 

but I've also check on the [php-src/ext/standard/basic_functions.c](https://github.com/php/php-src/blob/c631f1ee2b4248dcb2658def545ee8fdfe108cb6/ext/standard/basic_functions.c#L3976) source-code of php, and the arg seems to be an int:
```c
/* {{{ proto string long2ip(int proper_address)
   Converts an (IPv4) Internet network address into a string in Internet standard dotted format */
PHP_FUNCTION(long2ip)
{
```

How to fix that?
Thanks.

**Comment by phpipam** [comment]
Hi, you can change line 347 from
```php
{ return(long2ip($address)); }
```
to 
```php
{ return(long2ip(int() $address)); }
```

Maybe do a `print_r($address),` before that line to see what is being sent to function.

**Comment by Gilgalidd** [comment]
Hello,

Thanks for fast reply, but the value change:

From: string(10) "2887140096"
To   : int(2147483647)

And it return the wrong IP: string(15) "127.255.255.255"

**Comment by phpipam** [comment]
Are you on 32-bit system ?

**Comment by phpipam** [comment]
Ok,I had similar issues on phpipam and this helped:

```php
# make integer
if (PHP_INT_SIZE === 8) {
    $addresss = gmp_strval(gmp_and("0xffffffff", (int) $address ));
else {
    $addresss = gmp_strval(gmp_and("0xffffffff", $address ));
}
```

Put htis before line 347.

**Comment by avignat** [comment]
Same issue for me. Running on : 
```
PHP 7.1.9 (cli) (built: Aug 30 2017 18:56:29) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```
On `armv7l GNU/Linux`

**Comment by RonarPS** [comment]
Hi,

had a similar issue, while transforming my setup into a docker container. Solved it with that lines of code:

in the /functions/classes/class.common.php you can find the following line:
`if ($this->identify_address ($address) == "IPv4" ) 				{ return(long2ip($address)); }`

i changed the line to the following Code:

`if ($this->identify_address ($address) == "IPv4" ) { 
$myVar = $address;
$myVar= $myVar +0;
$int_myVar = intval($myVar);
return(long2ip($int_myVar)); 
}`

yes - if you like to, you can also make some shorter code :)

**Comment by GaryAllan** [comment]
Closing old thread. Please re-open if issue is still present (php-agent code has been updated)
Thank you
