### ISSUE TITLE
Agent for Windows

### ISSUE THREAD

**Issue by Gilgalidd** [phpipam/phpipam-agent#3]
Hey!

I'm trying to run agent under Windows, but the PCNTL module seems to be only available for Unix platform. Is it possible to run agent without this module ?

```
C:\php>php.exe C:\phpipam-agent-master\index.php -discover
--------------------
The following required PHP extensions are missing for phpipam-agent:
  - pcntl
Please recompile PHP to include missing extensions.
--------------------
```

```
C:\php>php.exe -v
PHP 5.4.45 (cli) (built: Sep  2 2015 23:48:00)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

**Comment by phpipam** [comment]
hi, yes that would be correct. Will add explicit switch in config to allow non-threaded agent checks. fping will be best option for this.

**Comment by Gilgalidd** [comment]
Hi,
I don't know if fping is a nice option, after some search, it seems to be complicated to use it under windows.
fping.exe is not wildly distributed, not available on cygwin repository, and some of fping.exe contain malaware.

**Comment by Gilgalidd** [comment]
I've finally find a fping ([dev.pulsed.net](http://dev.pulsed.net/wp/?p=3)) and it seems to be clean, controlled with [virustotal.com](https://www.virustotal.com/en/file/a2270785b4cf4a1a36fee2b0886d43874590ae036ebbff631bffdff058889db4/analysis/1445941779/).

Is it possible to disable the multi-thread manually?
I'm stuck with it and would like to do more tests :smiley:
