### ISSUE TITLE
php agent bug

### ISSUE THREAD

**Issue by mapaterson36** [phpipam/phpipam-agent#58]
When running the update and discovery scripts as cron jobs, I notice the following errors and nothing gets updated:

**Warning: sizeof(): Parameter must be an array or an object that implements Countable in /batch/agent/phpipam-agent/functions/classes/class.phpipamAgent.php on line 1092**

**PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /batch/agent/phpipam-agent/functions/classes/class.phpipamAgent.php on line 1092**

Cron causing these errors:
/usr/bin/php /batch/agent/phpipam-agent/index.php update
/usr/bin/php /batch/agent/phpipam-agent/index.php discover

PHPipam:  [v1.5] dbversion26
OS:  Ubuntu Linux 18.04.2
PHP 7.2.19-0
Webserver [Apache]
Database [MariaDB mariadb 10.1.23]

**Comment by GaryAllan** [comment]
Hi @mapaterson36
This should be fixed now (using latest phpipam-agent and phpipam 1.4/master).
Please re-open if you're still having issues
