### ISSUE TITLE
phpipam agent

### ISSUE THREAD

**Issue by joea24** [phpipam/phpipam-agent#59]
Posted this in the phpipam-agent area.  Anyone successfully using it?  Mine is saying invalid key.  Compare the key in the client vs. the host and they match.

https://github.com/phpipam/phpipam-agent/issues/52#issue-434803361

THanks.

**Comment by GaryAllan** [comment]
Hi @joea24 
This should be fixed now (using latest phpipam-agent and phpipam 1.4/master.
Please re-open if you're still having issues
