### ISSUE TITLE
ScanAgents are not scanning automatically 

### ISSUE THREAD

**Issue by passie** [phpipam/phpipam-agent#6]
For some reason the scanAgents are not scanning there subnet range automatically.
When I enforce an manual scan the range is scanned again for some time and then stops a couple hours later.
How can I debug this ?

**Comment by ernestneo** [comment]
You will need to create a cronjob to run the scanAgent periodically

eg. every 5mins interval

`
*/5 * * * * php /where/your/agent/index.php update
`

**Comment by phpipam** [comment]
As @ernestneo said, you need to schedule it from cron.

**Comment by Yoda-BZH** [comment]
Would it be possible to add this to the README ?

**Comment by phpipam** [comment]
Added.

**Comment by Yoda-BZH** [comment]
:+1: 
Thanks :)
