### ISSUE TITLE
How to use phpipam scan agent?

### ISSUE THREAD

**Issue by paulng30** [phpipam/phpipam-agent#67]
We have a working Ipam environment.  I am just now starting to configure an agent to scan subnets in a different location. The scan agent has been installed and can communicate with the ipam server mariadb.  

When run index.php from scan agent system, it returns nothing.  I know it can reach the server's database, but not sure if index.php did anything.

![image](https://user-images.githubusercontent.com/68069923/87071486-e873ea80-c1df-11ea-98ec-4409c755a538.png)

However, when look at the Scan Agents status from the Ipam server GUI, it shows that my Ipam scan agent never access the Ipam server.

![ScanAgentStatus](https://user-images.githubusercontent.com/68069923/87071077-553ab500-c1df-11ea-9020-e3e922ddd3e0.PNG)

My question is how do we configure for certain locations or subnets to use a specific scan agent?

**Comment by paulng30** [comment]
I just figured it out.  After assigned the agent to the created subnet,  ran the index.php discover, IP info started to populate the database.  Hope this helps whoever comes after me with these questions.

**Comment by artiomamerhanov** [comment]
How did you " assigned the agent to the created subnet"? Can't find it where it is?
thanks.
