### ISSUE TITLE
Undefined variable: db

### ISSUE THREAD

**Issue by grumpytwig** [phpipam/phpipam-agent#7]
Config options seem to be referenced incorrectly in the PDO class:

`Notice: Undefined variable: db in /var/www/html/phpipam-agent/functions/classes/class.PDO.php on line 63
etc. etc.
`
It seems they're being referenced as:

`$this->host     = $db['host'];`

but should be:

`$this->host     = $config['db']['host'];`

**Comment by phpipam** [comment]
Hi, agreed, but PDO is initiated in index.php, are only used if none is provided (as default values):

`$Database = new Database_PDO ($config['db']['user'], $config['db']['pass'], $config['db']['host'], $config['db']['port'], $config['db']['name']);`

Will remove set_db_params method.
