### ISSUE TITLE
Fatal error: Cannot redeclare class Database_PDO in /var/www/phpipam/functions/classes/class.PDO.php on line 9

### ISSUE THREAD

**Issue by burningrooftop** [phpipam/phpipam-agent#8]
Running on Debian 8 gives the following error:

`Fatal error: Cannot redeclare class Database_PDO in /var/www/phpipam/functions/classes/class.PDO.php on line 9`

Workaround is to wrap the Database_PDO class definition in class.PDO.php in an if statement:

`if (!class_exists('Database_PDO')) {
...
}`

Only the Database_PDO class definition should be inside the if statement, the abstract class DB definition should be outside the if statement.

I have no idea what the root cause is?

This issue was raised over at SourceForge (bug #381)

**Comment by phpipam** [comment]
Hi, can you output full error - usually it comes with "Already declared at..."

Which php version ?

**Comment by burningrooftop** [comment]
That is the full error message, no "Already declared at..." message appeared. However if I changed the name of the Database_PDO class in class.PDO.php, the class name in the error message changed as well - so somehow it seems to be loading class.PDO.php twice.

I had this same installation running with no problems on a CentOS 7 host (not sure what php version) before I moved it to the current Debian host.

PHP version info:

`PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with XCache Optimizer v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Coverager v3.2.0, Copyright (c) 2005-2014, by mOo`

**Comment by burningrooftop** [comment]
Further information...

If I move the definition of the abstract class DB to the start of  the class.PDO.php file (ie put it before the Database_PDO class definition), the problem goes away (no if statement required).

**Comment by phpipam** [comment]
Strange, will upgrade my php to 5.6 when I have tome to test.

Fount this though, same as yours, if class b that extends a is defined first:
https://bugs.php.net/bug.php?id=68698&thanks=3

> Found this bug active on debian jessie with PHP Version 5.6.17

**Comment by phpipam** [comment]
Hm...

http://php.net/manual/en/keyword.extends.php

> Note:
Classes must be defined before they are used! If you want the class Named_Cart to extend the class Cart, you will have to define the class Cart first. ... To make it short: the order in which the classes are defined is important.

than this:

> Note:
Unless autoloading is used, then classes must be defined before they are used. If a class extends another, then the parent class must be declared before the child class structure. This rule applies to classes that inherit other classes and interfaces.

Seems linke smth changed in new version. Will move DB before Database_PDO.

**Comment by phpipam** [comment]
I updated MASTER, please test.

br

**Comment by burningrooftop** [comment]
This issue is fixed in MASTER.
