### ISSUE TITLE
Invalid connection type!

### ISSUE THREAD

**Issue by RobyRWK** [phpipam/phpipam-agent#83]
Hi everyone, I have a problem, I can't connect to phpipam.
if I try a telnet on port 3306 it works fine.
I also tried to install the mysql client and I can connect with the user and password, but when I start index.php this is the result:
```[xx@ipam-p2:/phpipam-agent]$ sudo php index.php
--------------------
Invalid connection type!
--------------------
[xx@ipam-p2:/phpipam-agent]$ sudo php index.php discover
--------------------
Invalid connection type!
```

the configuration of config.dist.php:
```
<?php

/* phpipam agent config file
  ******************************/

# set connection type
# api,mysql;
# ******************************/
$config['type'] = "mysql";
# set agent key
# ******************************/
$config['key'] = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

# set scan method and path to ping file
# ping, fping or pear
# ******************************/
//$config['method'] = "pear";
//$config['pingpath'] = "/sbin/ping";

$config['method'] = "fping";
$config['pingpath'] = "/usr/bin/fping";

# permit non-threaded checks (default: false)
# ******************************/
$config['nonthreaded'] = false;

# how many concurrent threads (default: 32)
# ****************************************/
$config['threads'] = 32;

# api settings, if api selected
# ******************************/
#$config['api']['key'] = "";

# send mail diff
# ******************************/
$config['sendmail'] = false;

# remove inactive DHCP addresses
#
# reset_autodiscover_addresses: will remove addresses if description -- autodiscovered -- and is offline
# remove_inactive_dhcp : will remove inactive dhcp addresses
# ******************************/
$config['reset_autodiscover_addresses'] = false;
$config['remove_inactive_dhcp'] = false;


# mysql db settings, if mysql selected
# ******************************/
$config['db']['host'] = "ipam.xx.xx";
$config['db']['user'] = "phpipam";
$config['db']['pass'] = "secretpassword:)";
$config['db']['name'] = "phpipam";
$config['db']['port'] = 3306;

/**
  * SSL options for MySQL
  *
  See http://php.net/manual/en/ref.pdo-mysql.php
      https://dev.mysql.com/doc/refman/5.7/en/ssl-options.html

      Please update these settings before setting 'ssl' to true.
      All settings can be commented out or set to NULL if not needed

      php 5.3.7 required
  ******************************/
#$config['db']['ssl'] = false; // true/false, enable or disable SSL as a whole
#$config['db']['ssl_key'] = '/path/to/cert.key'; // path to an SSL key file. Only makes sense combined with ssl_cert
#$config['db']['ssl_cert'] = '/path/to/cert.crt'; // path to an SSL certificate file. Only makes sense combined with ssl_key
#$config['db']['ssl_ca'] = '/path/to/ca.crt'; // path to a file containing SSL CA certs
#$config['db']['ssl_capath'] = '/path/to/ca_certs'; // path to a directory containing CA certs
#$config['db']['ssl_cipher'] = 'DHE-RSA-AES256-SHA:AES128-SHA'; // one or more SSL Ciphers
#$config['db']['ssl_verify'] = true; // Verify Common Name (CN) of server certificate?`

/ ``
```
Do you have any idea what I'm doing wrong?

I "hid" the following information:
```
$config['key'] = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
$config['db']['host'] = "ipam.xx.xx";
$config['db']['pass'] = "secretpassword:)";
```
thx!

**Comment by RobyRWK** [comment]
does anyone have any ideas?

**Comment by Kendzione** [comment]
You need to have "key" matching  in scan-agents secion in ipam GUI.
Your config looks vaild. Ipam.xx.xx resolves to your ip address?  Can you verify what happens in database logs during evecution? Is database name and credentials  correct?  Remote logins allowed?

**Comment by Kendzione** [comment]
And does your database allow unencrypted connections?

**Comment by Kendzione** [comment]
Does this user has write permission to database?

**Comment by Kendzione** [comment]
And did you installed php plugins ? pdo, pdo_mysql

**Comment by RobyRWK** [comment]
> You need to have "key" matching in scan-agents secion in ipam GUI. Your config looks vaild. Ipam.xx.xx resolves to your ip address? Can you verify what happens in database logs during evecution? Is database name and credentials correct? Remote logins allowed?

Thanks for your answer!
yes, the key is correct.
I solve correctly if I try to connect like this it works:
  sudo mysql -u phpipam -pXXXXXXX -h ipam.xx.xx
and I enter mysql>

**Comment by RobyRWK** [comment]
> Does this user has write permission to database?

yes write and delete

**Comment by RobyRWK** [comment]
between the two vms there is a firewall where I check the connection logs, when I use the commands:
"sudo mysql -u phpipam -pXXXXXXX -h ipam.xx.xx"
I see the connections on port 3306 and it works,
when I try "sudo php index.php update" I don't see any logs,
I think there are some blocks even before reaching the mysql

**Comment by phpipam** [comment]
try this:
`cp config.dist.php config.php`

**Comment by RobyRWK** [comment]
The problem was in the class.Config.php file which was modified (I don't know by which process) like this:
     private static function read_config() {
         #require( dirname(__FILE__)."/../../config.php" );
         require( dirname(__FILE__)."/../PHPMailer/.phan/config.php" );
         self::$config = (object) get_defined_vars();

modifying it like this:
     private static function read_config() {
         require( dirname(__FILE__)."/../../config.php" );
         #require( dirname(__FILE__)."/../PHPMailer/.phan/config.php" );
         self::$config = (object) get_defined_vars();

and following the advice of the following command:
cp config.dist.php config.php

it worked!
thank you all
